version: '2'
services:
  elasticsearch:
    image: elasticsearch:5
    ports:
      - 9200:9200
    environment:
      - ES_JAVA_OPTS=-Xms1G -Xmx1G
  kibana:
    image: kibana:5
    ports:
      - 5601:5601
    links:
      - elasticsearch:elasticsearch
